name: abalone-mlops
channels:
  - conda-forge
dependencies:
  - python=3.10
  - seaborn=0.12.2
  - scikit-learn=1.3.1
  - ipykernel=6.25.2
  - pandas=2.1.1
  - loguru=0.7.2
  - mlflow=2.7.1
  - uvicorn=0.23.2
  - fastapi=0.103.2
  - prefect=2.13.7
  - pydantic<2
  - pre-commit
  - black=22.12.0
  - flake8=6.0.0
  - isort=5.12.0
  - pip
  - pip:
      - black[jupyter]
